README.md

Rename to scaffold

---

dist/manifest.json

:v:
Updated `frameworkVersion` from `1.0` to `2.0`
* JIRA: 
* Current users of the scaffold will need to update the manifest `frameworkVersion`

updated frameworkVersion to 2.0

---

src/javascripts/base_app.js

:v:
* JIRA: https://zendesk.atlassian.net/browse/AF-384
* [low] local storage may not work correctly for migrated v1 apps

[AF-384] Scope localStorage per installation

---

lib/javascripts/base_app.js
lib/javascripts/i18n.js
lib/javascripts/storage.js
lib/javascripts/view.js
src/javascripts/index.js
src/javascripts/legacy_app.js

:v:
This is so we can reuse `View` and `Storage` when writing v2 apps from scratch using [this branch](https://github.com/zendesk/app_scaffold/compare/daniel/from-scratch...daniel/from-scratch-scaffold).

Refactor for reusability

---

README.md

:v:
/cc @zendesk/vegemite @chucknado

Document from-scratch branch

---

dist/assets/index.html
webpack.config.js

/cc @zendesk/vegemite 
This fixes an issue with the app scaffold where the browser complains about mixed content since the external assets were being requested using the 'http' protocol, rather than 'https'.

Externals fix

---

dist/assets/index.html
webpack.config.js

Add proper HTTPS URIs on necessary files that fixes #23

Error ZAFClient not defined

---

package.json

Bump handlebars-loader

---

src/javascripts/ticket_sidebar.js

Fix resize call

---

lib/javascripts/base_app.js
src/javascripts/legacy_app.js
src/templates/main.hdbs
src/templates/modal.hdbs

add and use a helper for opening modals

---

lib/javascripts/base_app.js
spec/lib/base_app_spec.js
spec/src/legacy_app_spec.js
src/javascripts/legacy_app.js

`BaseApp` now calls the `app.willDestroy` handler when the window unload event fires.
cc @zendesk/vegemite

example and shim for app.willDestroy

---

lib/javascripts/base_app.js
src/javascripts/legacy_app.js
src/templates/main.hdbs
src/templates/modal.hdbs

This reverts commit 6f79b47bcc484982ca00fd85b864e122db3f8757, reversing
changes made to 3d74d7e59130ec6ac92067f6be081d3de854cf41.
cc @zendesk/vegemite

Revert "Merge pull request #31 from zendesk/roman/modal"

---

dist/manifest.json

Update location in the manifest

---

README.md

document use of zat to deploy apps. Fixes #21

---

README.md

List features provided by the scaffold and document folder structure.

---

webpack.config.js

:v:
Solves #44.
/cc @zendesk/vegemite @wcactus @corneliuskopp

Fix issue with translations not being loaded on windows

---

webpack.config.js

:v:
See https://github.com/zendesk/app_scaffold/pull/52.
/cc @zendesk/vegemite @joelhellman

Fix handlebars image requires

---

webpack.config.js

Remove moment.js

---

webpack.config.js

:v:
Update Garden version so people using the from-scratch branch have the latest version available.

Update Garden version

---

doc/i18n.md

Remove misleading message

---

src/translations/en.json

@zendesk/wombat 
@zendesk/vegemite 
Reflecting the upcoming change on `apps_approval`
* JIRA: https://zendesk.atlassian.net/browse/CACT-176
* low

[CACT-176] Translations to reflect upcoming change on apps_approval

---

karma.conf.js
lib/javascripts/base_app.js
package.json
spec/lib/base_app_spec.js
webpack.config.js

@zendesk/vegemite 
Make $.when compatible with native promises. See https://stackoverflow.com/a/36255846.

Make $.when compatible with native promises

---

lib/javascripts/base_app.js

Add this.trigger API shim

---

lib/javascripts/base_app.js
spec/lib/view_spec.js

✌️ 
cc @zendesk/vegemite 
To assist with migration of a v1 app, provide an `assetURL` Handlebars helper.  The helper will rewrite URLs to be relative to the v2 assets directory from which HTML is served.
- N/A

Add assetURL Handlebars helper

---

webpack.config.js

Could not use partials because of this.

Use correct extensions for handlebars-loader

---

webpack.config.js

zendesk garden css v2 url update for the from-scratch branch

Updates webpack css external assets to v2 url

---

DEPLOY.md
README.md
doc/adrs/replace-migration-scaffold-with-clean-scaffold-in-master-branch.md
doc/i18n.md

[OFFAPPS-1037] Replace master branch with offapps-migration branch. Create new readme documentation and ADR
This PR is part of ticket [OFFAPPS-1037](https://zendesk.atlassian.net/browse/OFFAPPS-1037), including changes and additions to the new scaffold documentation
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1037)
@zendesk/apps-migration
@zendesk/vegemite

[OFFAPPS-1037] New scaffold documentations
